"""
Django settings for pepe project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_46x$-rh6(x%8j+*0s*c62)vv^&lx9z6w(9p%ksiod_ll+mz%#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'pepe-ptit.onrender.com',
    'localhost',
    '127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    "accounts",
    "forum",
    "home",
    "search",
    "wallet",
    
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.staticfiles"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pepe.urls"
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_HTTPONLY = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pepe.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        # Default: sqlite for local dev. To use Postgres, set environment variables.
        "ENGINE": os.environ.get('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3'),
        "NAME": os.environ.get('DJANGO_DB_NAME', str(BASE_DIR / 'example.sqlite3')),
        "USER": os.environ.get('DJANGO_DB_USER', ''),
        "PASSWORD": os.environ.get('DJANGO_DB_PASSWORD', ''),
        "HOST": os.environ.get('DJANGO_DB_HOST', ''),
        "PORT": os.environ.get('DJANGO_DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Bangkok"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (Uploaded files)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * (1024 ** 2)  # 25MB
DATA_UPLOAD_MAX_MEMORY_SIZE = FILE_UPLOAD_MAX_MEMORY_SIZE

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cấu hình Blockchain
HSCOIN_API_BASE_URL="https://hsc-w3oq.onrender.com/api" # URL mạng blockchain của bạn
HSCOIN_API_KEY="2dbf580f5c634947ba4f29935570cc4d"
# CHAIN_ID = 1337 # Thay bằng Chain ID mạng của bạn (thường 1337 hoặc xem trên web)
HSCOIN_ADMIN_EMAIL="namhoangtran191@gmail.com"
HSCOIN_ADMIN_PASSWORD=123456

# Smart Contract Address (SimpleToken)
HSCOIN_SIMPLE_TOKEN_ADDRESS=0x773d5787b8afcfd11aa04fdd73b792da4134ffce

# Danh sách ví được phép gọi contract
HSCOIN_ALLOWED_CALLERS=0xc839fb60d86b9838f5772c33dc1f77c67fd809e7,0x693d7eeac22122406e49df7a84a23382fa272748
# VÍ 1 (ADMIN) - Dùng để Mint token cho user
ADMIN_WALLET_ADDRESS = "0xc839fb60d86b9838f5772c33dc1f77c67fd809e7" 
ADMIN_PRIVATE_KEY = "0dc35a6279ce936b5e123e028ac6ea8c715d68ca8a5aee2bfc8ac61b2d1b17d8"

TOKEN_CONTRACT_ADDRESS = "0x39b86e79657fbccacf4437f119916d611ec21095"