"""
Django settings for pepe project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_46x$-rh6(x%8j+*0s*c62)vv^&lx9z6w(9p%ksiod_ll+mz%#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'pepe-ptit.onrender.com',
    'localhost',
    '127.0.0.1'
]

# Application definition

INSTALLED_APPS = [
    "accounts",
    "forum",
    "home",
    "search",
    "wallet",
    
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.staticfiles"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pepe.urls"
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_HTTPONLY = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pepe.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        # Default: sqlite for local dev. To use Postgres, set environment variables.
        "ENGINE": os.environ.get('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3'),
        "NAME": os.environ.get('DJANGO_DB_NAME', str(BASE_DIR / 'example.sqlite3')),
        "USER": os.environ.get('DJANGO_DB_USER', ''),
        "PASSWORD": os.environ.get('DJANGO_DB_PASSWORD', ''),
        "HOST": os.environ.get('DJANGO_DB_HOST', ''),
        "PORT": os.environ.get('DJANGO_DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Bangkok"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (Uploaded files)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * (1024 ** 2)  # 25MB
DATA_UPLOAD_MAX_MEMORY_SIZE = FILE_UPLOAD_MAX_MEMORY_SIZE

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cấu hình Blockchain
HSCOIN_API_BASE_URL="https://hsc-w3oq.onrender.com/api" # URL mạng blockchain của bạn
HSCOIN_API_KEY="30ee8479531340b497f4069ec873a498"
# CHAIN_ID = 1337 # Thay bằng Chain ID mạng của bạn (thường 1337 hoặc xem trên web)

# Smart Contract Address (SimpleToken)
# HSCOIN_SIMPLE_TOKEN_ADDRESS=0x773d5787b8afcfd11aa04fdd73b792da4134ffce

# Danh sách ví được phép gọi contract
HSCOIN_ALLOWED_CALLERS=0xc839fb60d86b9838f5772c33dc1f77c67fd809e7,0x693d7eeac22122406e49df7a84a23382fa272748
# VÍ 1 (ADMIN) - Dùng để Mint token cho user
ADMIN_WALLET_ADDRESS = "0xc839fb60d86b9838f5772c33dc1f77c67fd809e7" 
ADMIN_PRIVATE_KEY = os.environ.get("PEPE_ADMIN_PK")

TOKEN_CONTRACT_ADDRESS = "0x25878fecdcb0a47187404ea6f1ddee9a4f455fff"
# WARNING: When True, private keys will be stored in the DB as plaintext.
# This is insecure. Only enable if you accept the risks.
# For normal operation we store keys encrypted; set to True only if you
# explicitly want plaintext storage.
STORE_PRIVATE_KEYS_PLAINTEXT = False


# --- CẤU HÌNH KHÓA MÃ HÓA VÍ (FERNET KEY) ---
# Đọc khóa mã hóa từ biến môi trường PEPE_CRYPTO_KEY.
# Khóa này phải là một chuỗi Base64 (ví dụ: 'k9sRzR7eW3Q-G2oXy5KxJ8vVl_aB0I2N-pA4tZ0cM0s=')

# python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# $env:PEPE_CRYPTO_KEY="UTKkSuqLi4myBkud0dmzM-pVXh7v-KbSzoSjmHVJ6CY="
# $env:PEPE_ADMIN_PK="[0dc35a6279ce936b5e123e028ac6ea8c715d68ca8a5aee2bfc8ac61b2d1b17d8]"
# python manage.py runserver

FERNET_KEY = os.environ.get("PEPE_CRYPTO_KEY")

if not FERNET_KEY:
    if DEBUG:
        # Tùy chọn: Trong môi trường DEV, sử dụng khóa mặc định và in cảnh báo
        print("CẢNH BÁO BẢO MẬT: Đang sử dụng khóa Fernet mặc định cho môi trường DEBUG. KHÔNG SỬ DỤNG CHO PRODUCTION!")
        FERNET_KEY = "8sTj6H-4k_5qL9oR2pZ1xV3mN7bA0cE8wY5dF2gH4jK=" # Dùng lại giá trị FIXED_KEY cũ
    else:
        # BẮT BUỘC: Trong môi trường Production (DEBUG=False), phải có khóa
        raise EnvironmentError("LỖI BẢO MẬT: Biến môi trường 'PEPE_CRYPTO_KEY' chưa được đặt. Hệ thống không thể chạy an toàn.")